{{- include "hallpass.validate" . -}}
{{- if .Values.apiKey.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hallpass.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hallpass.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.apiKey.key }}: {{ .Values.apiKey.value | quote }}
{{- end }}
